run:
  tests: false
  timeout: 10m
  skip-dirs:
    - example/
    - mocks/
linters:
  enable-all: true
  disable:
    - wrapcheck
    - exhaustivestruct
    - ireturn
    - godot
    - interfacebloat
    - deadcode # is deprecated (since v1.49.0)
    - structcheck # is deprecated (since v1.49.0)
    - scopelint # is deprecated (since v1.39.0)
    - golint # is deprecated (since v1.41.0)
    - interfacer # is deprecated (since v1.38.0)
    - maligned # is deprecated (since v1.38.0)
    - ifshort # is deprecated (since v1.48.0)
    - nosnakecase # is deprecated (since v1.48.1)
    - varcheck # is deprecated (since v1.49.0)
  fast: true
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated

  govet:
    enable-all: true
    disable:
      - shadow

  gci:
    local-prefixes: github.com/loghole/tracing

  varnamelen:
    # The longest distance, in source lines, that is being considered a "small scope." (defaults to 5)
    # Variables used in at most this many lines will be ignored.
    max-distance: 10
    # Ignore "ok" variables that hold the bool return value of a type assertion. (defaults to false)
    ignore-type-assert-ok: true
    # Ignore "ok" variables that hold the bool return value of a map index. (defaults to false)
    ignore-map-index-ok: true
    # Ignore "ok" variables that hold the bool return value of a channel receive. (defaults to false)
    ignore-chan-recv-ok: true
    # Optional list of variable names that should be ignored completely. (defaults to empty list)
    ignore-names:
      - db
      - ok
      - fn
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request
      - wg sync.WaitGroup
      - cc *grpc.ClientConn
      - ss grpc.ServerStream
      - wr *wrapper
